name: Devhub Migration

env:
  DEVHUB_BASE_URL: https://dev-hub-0008-api.dev.core-services.developer-platform.io
  DEVHUB_MIGRATION_SOURCE_DIR: sdbmigration
  DEVHUB_OUTPUT_DIR: devhub

on:
  pull_request:
    types: [opened, synchronize, ready_for_review]
    paths:
      - "catalog-info.yaml"
      - "backstage/**/*.yaml"
      - "backstage/**/*.yml"
      - "backstage/**/*.*.yaml"
      - "backstage/**/*.*.yml"
      - "sdbmigration/**/*.yaml"
      - "sdbmigration/**/*.yml"
      - "sdbmigration/**/*.*.yaml"
      - "sdbmigration/**/*.*.yml"
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  translate:
    name: DevHub Migration
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Get Migration Tools
        run: |
          mkdir tools
          curl -H "Authorization: token $secrets.ACCESS_TOKEN" https://raw.githubusercontent.com/deliveryhero/dh-devhub-migrator/main/dist/debhub_cli_linux --output tools/devhub_cli
          curl -H "Authorization: token $secrets.ACCESS_TOKEN" https://raw.githubusercontent.com/deliveryhero/dh-devhub-migrator/main/dist/debhub_migration_linux --output tools/devhub_migration
          chmod +x tools/devhub_cli
          chmod +x tools/devhub_migration
      - name: Run Migration Tool
        run: |
          cd tools
          ./devhub_migration --SOURCE_DIR ../$DEVHUB_MIGRATION_SOURCE_DIR --OUTPUT_DIR ../$DEVHUB_OUTPUT_DIR 
      - name: Get Generated Yaml Files
        id: lister
        uses: Rishabh510/Path-lister-action@master
        with:
          path: env.DEVHUB_OUTPUT_DIR
          type: ".yaml"
      - name: Run Devhub CLI Save
        run: |
          cd tools
          echo "Found ${{ steps.lister.outputs.path_count }} file(s) with this extension:"
          echo "To generate the file output use arg -o ${i/devhub\//cli\/} on CLI (devhub_cli) command"
          for i in ${{ steps.lister.outputs.paths }}; do
            echo "---------------------> Start Processing File: $i"
            ./devhub_cli save -i ../$i -eo ../${i/\.yaml/.error.json} -dr
          done
      - name: Get Changed Yaml Files
        id: changed-entities
        uses: tj-actions/changed-files@v35
        with:
          files: ${{env.DEVHUB_OUTPUT_DIR}}/**/*.{yaml,yml}
      - name: Validate Devhub CLI output
        id: validation
        run: |
          echo "IS_VALID=true" >> $GITHUB_OUTPUT
          for f in ${{ steps.changed-entities.outputs.all_changed_files }}; do
            echo "---------------------> Start Validation of File: $f"
            if test -f ${f/\.yaml/.error.json}; then
                echo "IS_VALID=false" >> $GITHUB_OUTPUT
                break
            fi
          done
      - name: Add Validation Labels
        uses: actions-ecosystem/action-add-labels@v1
        if: ${{ steps.validation.outputs.IS_VALID == 'false' }}
        with:
          labels: devhub-error
      - name: Remove Validation Labels
        uses: actions-ecosystem/action-remove-labels@v1
        if: ${{ steps.validation.outputs.IS_VALID == 'true' }}
        with:
          labels: devhub-error
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Darian Campos
          author_email: darian.campos@pedidosya.com
          message: 'Migration success'
          add: 'devhub/ --force'
      - name: Fail Checks
        if: ${{ steps.validation.outputs.IS_VALID == 'false' }}
        run: exit 1