name: Migration Churrera

env:
  DEVHUB_BASE_URL: https://dev-hub-0008-api.dev.core-services.developer-platform.io

on:
  pull_request:
    types: [opened, synchronize, ready_for_review]
    paths:
      - "catalog-info.yaml"
      - "backstage/**/*.yaml"
      - "backstage/**/*.yml"
      - "backstage/**/*.*.yaml"
      - "backstage/**/*.*.yml"
      - "sdbmigration/**/*.yaml"
      - "sdbmigration/**/*.yml"
      - "sdbmigration/**/*.*.yaml"
      - "sdbmigration/**/*.*.yml"
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  translate:
    name: Migrations files
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Clone Python Migration Repository
        uses: actions/checkout@v3
        with:
          repository: deliveryhero/dh-devhub-migrator
          path: dh-devhub-migrator
          token: ${{ secrets.ACCESS_TOKEN }}
          ref: testCli
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install Python Dependencies
        run: |
          cd dh-devhub-migrator
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint Python with flake8
        run: |
          cd dh-devhub-migrator
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Run Migration Tool
        run: |
          python3 dh-devhub-migrator/extract_entities.py  --SOURCE_DIR sdbmigration --OUTPUT_DIR devhub
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Darian Campos
          author_email: darian.campos@pedidosya.com
          message: 'Migration success'
          add: 'devhub/ --force'
      - name: Fetch Migration Files
        id: lister
        uses: Rishabh510/Path-lister-action@master
        with:
          path: "devhub"
          type: ".yaml"

      - name: Output results
        run: |
          echo "Found ${{ steps.lister.outputs.path_count }} file(s) with this extension:"
          for i in ${{ steps.lister.outputs.paths }}; do
            python dh-devhub-migrator/cli/ultron.py save -i $i -eo ${i/\.yaml/.error.json} -dr
            echo "If need to be generated the output use arg -o ${i/devhub\//cli\/} on CLI (ultron) command"
          done
