name: Devhub Migration Check

env:
  DEVHUB_BASE_URL: https://dev-hub-0008-api.dev.core-services.developer-platform.io
  DEVHUB_MIGRATION_SOURCE_DIR: sdbmigration
  DEVHUB_OUTPUT_DIR: devhub

on:
  pull_request:
    types: [opened, synchronize, ready_for_review]
    paths:
      - "catalog-info.yaml"
      - "backstage/**/*.yaml"
      - "backstage/**/*.yml"
      - "backstage/**/*.*.yaml"
      - "backstage/**/*.*.yml"
      - "sdbmigration/**/*.yaml"
      - "sdbmigration/**/*.yml"
      - "sdbmigration/**/*.*.yaml"
      - "sdbmigration/**/*.*.yml"
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  translate:
    name: DevHub Migration Check
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Checkout Migration Tools Repository
        uses: actions/checkout@v3
        with:
          repository: deliveryhero/dh-devhub-migrator
          path: tools
          token: ${{ secrets.ACCESS_TOKEN }}
          ref: main
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install Python Dependencies And Requirements
        run: |
          cd tools
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint Python Files with flake8
        run: |
          cd tools
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Run Migration Tool
        run: python tools/extract_entities.py  --SOURCE_DIR $DEVHUB_MIGRATION_SOURCE_DIR --OUTPUT_DIR $DEVHUB_OUTPUT_DIR 
      - name: Get Generated Yaml Files
        id: lister
        uses: Rishabh510/Path-lister-action@master
        with:
          path: env.DEVHUB_OUTPUT_DIR
          type: ".yaml"
      - name: Run Devhub CLI Save
        run: |
          echo "Found ${{ steps.lister.outputs.path_count }} file(s) with this extension:"
          echo "To generate the file output use arg -o ${i/devhub\//cli\/} on CLI (devhub_cli) command"
          for i in ${{ steps.lister.outputs.paths }}; do
            echo "---------------------> Start Processing File: $i"
            python tools/cli/devhub_cli.py save -i $i -eo ${i/\.yaml/.error.json} -dr
          done
      - name: Get Changed Yaml Files
        id: changed-entities
        uses: tj-actions/changed-files@v35
        with:
          files: ${{env.DEVHUB_OUTPUT_DIR}}/**/*.{yaml,yml}
      - name: Validate Devhub CLI output
        id: validation
        run: |
          echo "IS_VALID=true" >> $GITHUB_OUTPUT
          for f in ${{ steps.changed-entities.outputs.all_changed_files }}; do
            echo "---------------------> Start Validation of File: $f"
            if test -f ${f/\.yaml/.error.json}; then
                echo "IS_VALID=false" >> $GITHUB_OUTPUT
                break
            fi
          done
      - name: Add Validation Labels
        uses: actions-ecosystem/action-add-labels@v1
        if: ${{ steps.validation.outputs.IS_VALID == 'false' }}
        with:
          labels: devhub-error
      - name: Remove Validation Labels
        uses: actions-ecosystem/action-remove-labels@v1
        if: ${{ steps.validation.outputs.IS_VALID == 'true' }}
        with:
          labels: devhub-error
      - name: Add Devhub Changed Label
        uses: actions-ecosystem/action-add-labels@v1
        if: ${{ steps.validation.outputs.IS_VALID == 'true' }}
        with:
          labels: devhub-ok
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Darian Campos
          author_email: darian.campos@pedidosya.com
          message: 'Migration success'
          add: 'devhub/ --force'
      - name: Fail Checks
        if: ${{ steps.validation.outputs.IS_VALID == 'false' }}
        run: exit 1
