name: Devhub Migration Push

env:
  DEVHUB_BASE_URL: https://dev-hub-0008-api.dev.core-services.developer-platform.io

on:
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  checklabel:
    name: Check DevHub Ok
    runs-on: ubuntu-latest
    steps:
      - name: Check devhub-ok Label
        id: check_devhub-ok
        uses: shioyang/check-pr-labels-on-push-action@v1.0.9
        with:
          labels: '["devhub-ok"]'
        timeout-minutes: 5
      - name: return result
        run: echo "${{ steps.check_devhub-ok.outputs.result }}"  >> $GITHUB_ENV
  pushdevhub:
    if: ${{ env.checklabel == 'true' }}
    name: DevHub Migration Push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Checkout Python Migration Scripts Repository
        uses: actions/checkout@v3
        with:
          repository: deliveryhero/dh-devhub-migrator
          path: dh-devhub-migrator
          token: ${{ secrets.ACCESS_TOKEN }}
          ref: main
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install Python Dependencies And Requirements
        run: |
          cd dh-devhub-migrator
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint Python Files with flake8
        run: |
          cd dh-devhub-migrator
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Get Generated Migration Files
        id: lister
        uses: Rishabh510/Path-lister-action@master
        with:
          path: "devhub"
          type: ".yaml"
      - name: Run Devhub CLI Save Command
        run: |
          echo "Found ${{ steps.lister.outputs.path_count }} file(s) with this extension:"
          echo "To generate the file output use arg -o ${i/devhub\//cli\/} on CLI (devhub_cli) command"
          for i in ${{ steps.lister.outputs.paths }}; do
            echo "---------------------> Start Processing File: $i"
            python dh-devhub-migrator/cli/devhub_cli.py save -i $i -dr 
            echo "---------------------> End Processing File $i"
          done