name: Devhub Migration Push

env:
  DEVHUB_BASE_URL: https://dev-hub-0008-api.dev.core-services.developer-platform.io

on:
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  if_merged:
    name: DevHub Migration Push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Checkout Python Migration Scripts Repository
        uses: actions/checkout@v3
        with:
          repository: deliveryhero/dh-devhub-migrator
          path: tools
          token: ${{ secrets.ACCESS_TOKEN }}
          ref: main
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install Python Dependencies And Requirements
        run: |
          cd tools
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint Python Files with flake8
        run: |
          cd tools
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Get Files
        id: listerFiles
        run: |
          python3 tools/list_files.py --INPUT_PATH=devhub --INPUT_TYPE=.yaml
      - name: Validate Devhub CLI output For Merge
        run: |
          for i in ${{ steps.listerFiles.outputs.paths }}; do
            echo "---------------------> Should push to Devhub, without dr option, File: $i"
            echo "---------------------> ${i/\.yaml/.error.json}"
            if test -f ${i/\.yaml/.error.json}; then
              echo "---------------------> $i not push by error"
            else
              echo "---------------------> SIN ERROR"
              python tools/cli/devhub_cli.py save -i $i -dr
            fi
          done 