name: Devhub Migration Push

env:
  DEVHUB_BASE_URL: https://dev-hub-0008-api.dev.core-services.developer-platform.io

on:
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  pushdevhub:
    name: DevHub Migration Push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Checkout Python Migration Scripts Repository
        uses: actions/checkout@v3
        with:
          repository: deliveryhero/dh-devhub-migrator
          path: dh-devhub-migrator
          token: ${{ secrets.ACCESS_TOKEN }}
          ref: main
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install Python Dependencies And Requirements
        run: |
          cd dh-devhub-migrator
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint Python Files with flake8
        run: |
          cd dh-devhub-migrator
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Get Generated Yaml Changed And Untracked Files
        id: listerChanges
        run: |
          python3 dh-devhub-migrator/list_files.py --INPUT_PATH=devhub --INPUT_TYPE=.yaml --ONLY_CHANGED
      - name: Get Generated Error Files
        id: listerError
        run: |
          python3 tools/list_files.py --INPUT_PATH=devhub --INPUT_TYPE=.error.json
      - name: Validate Devhub CLI output For Merge
        run: |
          echo "Found ${{ steps.listerChanges.outputs.path_count }} file(s) has changed:"
          for i in ${{ steps.listerChanges.outputs.paths }}; do
            echo "---------------------> Should push to Devhub, without dr option, File: $i"
            echo "---------------------> ${i/\.yaml/.error.json}"
            if [ ! ${i/\.yaml/.error.json} in ${{ steps.listerError.outputs.path }} ]; then
              echo "---------------------> SIN ERROR"
              python dh-devhub-migrator/cli/devhub_cli.py save -i $i -dr
            else
              echo "---------------------> $i not push by error"
            fi
          done 