name: Devhub Migration

env:
  DEVHUB_BASE_URL: https://dev-hub-0008-api.dev.core-services.developer-platform.io

on:
  pull_request:
    types: [merged]
    paths:
      - "catalog-info.yaml"
      - "backstage/**/*.yaml"
      - "backstage/**/*.yml"
      - "backstage/**/*.*.yaml"
      - "backstage/**/*.*.yml"
      - "sdbmigration/**/*.yaml"
      - "sdbmigration/**/*.yml"
      - "sdbmigration/**/*.*.yaml"
      - "sdbmigration/**/*.*.yml"
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  translate:
    name: DevHub Migration
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Get Generated Migration Files
        id: lister
        uses: Rishabh510/Path-lister-action@master
        with:
          path: "devhub"
          type: ".yaml"
      - name: Run Devhub CLI Save Command
        run: |
          echo "Found ${{ steps.lister.outputs.path_count }} file(s) with this extension:"
          echo "To generate the file output use arg -o ${i/devhub\//cli\/} on CLI (devhub_cli) command"
          for i in ${{ steps.lister.outputs.paths }}; do
            echo "---------------------> Start Processing File: $i"
            python dh-devhub-migrator/cli/devhub_cli.py save -i $i -dr
            echo "---------------------> End Processing File $i"
          done